jobs:
# jobs for the dv pipeline from CI thru TEST environment
# manifest gen for VISUALIZER
  - name: pipelines-demo-manifest
    type: manifest
    steps:
      - IN: samplepipelinesdemo
      - IN: samplepipelinesdemo-opts
      - TASK: managed

#/ manifest gen for VISUALIZER

# TEST deployment for VISUALIZER to Amazon ECS
  - name: pipelines-demo-deploy
    type: deploy
    steps:
      - IN: samplepipelinesdemo
      - IN: ecs-cluster
      - TASK: managed

# / TEST deployment for VISUALIZER to Amazon ECS

# Connect CI with dv-img resource
  - name: samplePipelinesDemo_runCI
    type: runCI
    steps:
      - IN: samplepipelinesdemo
      - OUT: ecs-cluster
# / Connect CI with dv-img resource
